name: Release Workflow

on:
  workflow_call:
    inputs:
      sdkVersion:
        required: true
        type: string
      releaseTag:
        required: true
        type: string

jobs:
  build:
    uses: danpowell88/OpenRVS/.github/workflows/compile-workflow.yml@master
    with:
      sdkVersion: ${{ inputs.sdkVersion }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: output
          merge-multiple: true
      - name: Copy extra files into output directory
        run: |
            cp openrvs.ini output/
            cp R6ClassDefines.ini output/
            cp Servers.list output/          
      - name: Zip all files in output directory
        run: |
          cd output
          zip -r ../OpenRVS-v${{ inputs.releaseTag }}.zip .       
      - name: Delete all assets from the release
        uses: mknejp/delete-release-assets@v1
        with:
          tag: v${{ inputs.releaseTag }}
          assets: "*"
          token: ${{ secrets.GITHUB_TOKEN }}          
          fail-if-no-release: false
          fail-if-no-assets: false
      - name: Create or update GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.releaseTag }}
          name: v${{ inputs.releaseTag }}
          files: |
            OpenRVS-v${{ inputs.releaseTag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
